# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: http://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
#  - repo: http://github.com/pre-commit/mirrors-mypy
#    rev: v1.6.1
#    hooks:
#      - id: mypy
#        entry: mypy
  - repo: http://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: http://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
